name: Backend CI/CD

# on:
#   push:
#     branches: [master]
#     paths:
#       - "sneaker-app-web/**"
#   pull_request:
#     branches: [master]
#     paths:
#       - "sneaker-app-web/**"
#

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Google Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.GCR_REGISTRY }}
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./sneaker-app-web
          push: true
          tags: ${{ secrets.GCR_REGISTRY }}/sneaker-app-web:latest

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy sneaker-app-web \
              --image ${{ secrets.GCR_REGISTRY }}/sneaker-app-web:latest \
              --platform managed \
              --region ${{ secrets.GCP_REGION }} \
              --allow-unauthenticated \
              --add-cloudsql-instances ${{ secrets.CLOUD_SQL_INSTANCE_NAME }} \
              --set-env-vars SPRING_DATASOURCE_URL=jdbc:postgresql:///sneaker_raffles?cloudSqlInstance=${{ secrets.CLOUD_SQL_INSTANCE_NAME }}&socketFactory=com.google.cloud.sql.postgres.SocketFactory,SPRING_DATASOURCE_USERNAME=${{ secrets.POSTGRES_USER }},SPRING_DATASOURCE_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
