name: CI/CD pipeline

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Convert GitHub owner to lowercase
        id: init
        run: echo "::set-output name=owner::$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ steps.init.outputs.owner }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: ./sneaker-app-web
          push: true
          tags: ghcr.io/${{ steps.init.outputs.owner }}/sneaker_raffle_proj/sneaker-app-web:latest

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: ./sneaker-raffle-app
          push: true
          tags: ghcr.io/${{ steps.init.outputs.owner }}/sneaker_raffle_proj/sneaker-raffle-app:latest

      - name: Authenticate to Google Cloud
        run: echo '${{ secrets.GCP_SA_KEY }}' | gcloud auth activate-service-account --key-file=-

      - name: Set Google Cloud Project
        run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy sneaker-app-web --image ghcr.io/${{ github.repository_owner }}/sneaker_raffle_proj/sneaker-app-web:latest --platform managed --region us-central1 --allow-unauthenticated
          gcloud run deploy sneaker-raffle-app --image ghcr.io/${{ github.repository_owner }}/sneaker_raffle_proj/sneaker-raffle-app:latest --platform managed --region us-central1 --allow-unauthenticated
