name: CI/CD pipeline

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: ./sneaker-app-web
          push: true
          tags: ghcr.io/${{ github.repository }}/sneaker-app-web:latest

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: ./sneaker-raffle-app
          push: true
          tags: ghcr.io/${{ github.repository }}/sneaker-raffle-app:latest

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@main
        with:
          service_account_key: ${{ secrets.GCLOUD_AUTH }}

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy sneaker-app-web --image ghcr.io/${{ github.repository }}/sneaker-app-web:latest --platform managed --region us-central1 --allow-unauthenticated
          gcloud run deploy sneaker-raffle-app --image ghcr.io/${{ github.repository }}/sneaker-raffle-app:latest --platform managed --region us-central1 --allow-unauthenticated
